export const REGISTER_START = "REGISTER_START";
export const REGISTER_END = "REGISTER_END";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const AUTHENTICATION_START = "AUTHENTICATION_START";
export const AUTHENTICATION_END = "AUTHENTICATION_END";
export const AUTHENTICATION_FAIL = "AUTHENTICATION_FAIL";
export const LOG_OUT = "LOG_OUT";

export const SET_USER_DATA = "SET_USER_DATA";
export const SET_CURR_USER_PROFILE_IMAGE = "SET_CURR_USER_PROFILE_IMAGE";
export const SET_UPDATE_PROFILE_LOADING = "SET_UPDATE_PROFILE_LOADING";
export const SET_PERSONAL_INFO = "SET_PERSONAL_INFO";
export const SET_FOLLOWED_USERS = "SET_FOLLOWED_USERS";

export const ADD_USER_POST = "ADD_USER_POST";
export const SET_NEW_POST_LOADING = "SET_NEW_POST_LOADING";
export const SET_GET_POSTS_LOADING = "SET_GET_POSTS_LOADING";
export const SET_UPDATE_POST_LOADING = "SET_UPDATE_POST_LOADING";
export const GET_USERS_POSTS = "GET_USERS_POSTS";
export const REMOVE_POST = "REMOVE_POST";
export const CLEAR_POSTS = "CLEAR_POSTS";
export const UPDATE_POST = "UPDATE_POST";

export const SET_SHOW_NAV = "SET_SHOW_NAV";
export const SET_SHOW_DISCOVER_BAR = "SET_SHOW_DISCOVER_BAR";

export const SET_LAST_CHAT = "SET_LAST_CHAT";
export const SET_CHAT_NOTIFICATIONS = "SET_CHAT_NOTIFICATIONS";
export const SET_CHAT = "SET_CHAT";
export const REMOVE_NOTIFICATIONS = "REMOVE_NOTIFICATIONS";
