export const REGISTER_START = "REGISTER_START";
export const REGISTER_END = "REGISTER_END";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const AUTHENTICATION_START = "AUTHENTICATION_START";
export const AUTHENTICATION_END = "AUTHENTICATION_END";
export const AUTHENTICATION_FAIL = "AUTHENTICATION_FAIL";
export const LOG_OUT = "LOG_OUT";

export const SET_DEFAULT_USER_DATA = "SET_DEFAULT_USER_DATA";

export const ADD_POST = "ADD_POST";
export const SET_LOADING = "SET_LOADING";
